// <auto-generated />
namespace BrunoFontes.Portifolio.Persistent.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migration_Initial_Create_Product_Brand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_Initial_Create_Product_Brand));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251627593_Migration_Initial_Create_Product_Brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
